# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rtypeset 0.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "rtypeset"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Trevor Fountain"]
  s.date = "2015-08-20"
  s.description = "A pure Ruby implementation of Typeset.js, an HTML pre-processor for web typography"
  s.email = "trevor@texasexpat.net"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "demo/demo.rb",
    "demo/raw.html",
    "demo/style.css",
    "demo/typeset.css",
    "index.html",
    "lib/typeset.rb",
    "lib/typeset/hanging_punctuation.rb",
    "lib/typeset/hyphenate.rb",
    "lib/typeset/ligatures.rb",
    "lib/typeset/punctuation.rb",
    "lib/typeset/quotes.rb",
    "lib/typeset/small_caps.rb",
    "lib/typeset/spaces.rb",
    "rtypeset.gemspec",
    "test/helper.rb",
    "test/test_typeset.rb"
  ]
  s.homepage = "http://github.com/doches/rtypeset"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.7"
  s.summary = "An HTML pre-processor for web typography"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<text-hyphen>, ["~> 1.4"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.6"])
      s.add_development_dependency(%q<minitest>, [">= 5.8.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<text-hyphen>, ["~> 1.4"])
      s.add_dependency(%q<nokogiri>, [">= 1.6"])
      s.add_dependency(%q<minitest>, [">= 5.8.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<text-hyphen>, ["~> 1.4"])
    s.add_dependency(%q<nokogiri>, [">= 1.6"])
    s.add_dependency(%q<minitest>, [">= 5.8.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

